constant('not:bool->bool')
constant('or:bool->bool->bool')
constant('=:?a->?a->bool')
constant('and:bool->bool->bool')
constant('implies:bool->bool->bool')
constant('iff:bool->bool->bool')
constant('schema:((obj->bool)->bool)->bool')
constant('for_all:(obj->bool)->bool')
constant('exists:(obj->bool)->bool')

operator('not', 1, 'right', 100)
operator('or', 2, 'left', 300)
operator('=', 2, 'left', 500)
operator('and', 2, 'left', 200)
operator('implies', 2, 'left', 300)
operator('iff', 2, 'left', 400)

binder('schema')
binder('for_all')
binder('exists')

definition(r'(and) = (\x.\y.(not ((not x) or (not y))))')
definition(r'(implies) = (\x.\y.((not x) or y))')
definition(r'(iff) = (\x.\y.((x implies y) and (y implies x)))')
definition(r'(exists) = (\x.(not (for_all y . (not (x(y))))))')
